### ISSUE TITLE
Option.getUnsafe does not raise

### ISSUE THREAD

**Issue by agarwal** [rescript-association/rescript-core#130]
The documentation of `Option.getUnsafe` gives the example:

> Option.getUnsafe(None) // Raises an error

However, the following code does not raise. I see `undefined` printed to the console and no exception.

```
let x = Option.getUnsafe(None)
Js.log(j`$x`)
```

Why is there also an `Option.getExn` function? That has the expected behavior, so I'm using that for now.

**Comment by glennsl** [comment]
The documentation is wrong. "Unsafe" here means that it's unsoundly typed, i.e. that it may return a value that does not belong to its return type.

**Comment by glennsl** [comment]
Proposed fix in #131
