### ISSUE TITLE
ReScript v11

### ISSUE THREAD

**Issue by zth** [rescript-association/rescript-core#132]
This tracks all the things we can/should do to fully utilize ReScript v11 in Core.

- [x] Dedicated JSON unboxed variant type. Enable this pattern: https://rescript-lang.org/blog/improving-interop#decoding-and-encoding-json-idiomatically
- [x] `Null.t` and `Nullable.t` should have an unboxed variant representation as well, so they can be pattern matched on.
- [ ] ~~Ensure that `Null.t` and `Nullable.t` have all the convenience functions that `Option` currently has, so they're smooth to work with~~ For later.
- [ ] `Promise.allSettled` bindings (cc @cometkim)

Please feel free to add your thoughts here. We'll fill in more things here as we go.

cc @cknitt @cristianoc

**Comment by youngkidwarrior** [comment]
I ran into this when upgrading to v11 as well in `/src/Core__Error.res`

`The unsafe j`$(a)$(b)` interpolation was removed, use string template `${a}${b}` instead.`

**Comment by zth** [comment]
This should be solved in `0.3.0`, please try that version.
