### ISSUE TITLE
Map.set returns unit

### ISSUE THREAD

**Issue by TomiS** [rescript-association/rescript-core#158]
Accoding to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set) `Map.set` returns the map itself. In bindings it only returns `unit`.

Is it intentional because `Map.set` mutates the map or is it a bug? Being able to chain would be quite nice.

**Comment by cknitt** [comment]
Yes, this is intentional because it is a mutable API.

**Comment by TomiS** [comment]
Ok. Makes sense. Thanks for confirmation.
