### ISSUE TITLE
Curious why changing the order of arguments for reduce?

### ISSUE THREAD

**Issue by DZakh** [rescript-association/rescript-core#165]
https://github.com/rescript-association/rescript-core/blob/ffca0a6e71cb388d040fcf08ce951876185ced9b/src/Core__Array.res#L168

A new ReScript developer approached me asking why their code doesn't compile. The problem was that they passed arguments to reduce in the JS-like order instead of passing the initial value first.

I don't have problems with it myself. Just a matter of habit. But this case showed me that it might be a problem for newcomers. Also it goes against the goal of the library:

> A drop-in standard library for ReScript. Intended to be familiar for JavaScript developers

**Comment by zth** [comment]
Point 3 in the guiding principles covers why: https://github.com/rescript-association/rescript-core#guiding-principles

Hint: This argument order for reduce gives better inference than the alternative, and we consider that more valuable than following the exact JS API in this particular case.
