### ISSUE TITLE
Missing Dict.getUnsafe

### ISSUE THREAD

**Issue by DZakh** [rescript-association/rescript-core#166]
I've just noticed that `Dict.getUnsafe` disappeared from the stdlib. Is it intentional? What's the reason? It's the function I use very often, so I'm confused.

**Comment by zth** [comment]
Was this removed from Core or just never added? I don't see a reason to not have it.

**Comment by DZakh** [comment]
I'll create a PR

**Comment by DZakh** [comment]
Fixed in https://github.com/rescript-association/rescript-core/pull/167
