### ISSUE TITLE
Missing `Number.MAX_SAFE_INTEGER` and `Number.MIN_SAFE_INTEGER`

### ISSUE THREAD

**Issue by dsiu** [rescript-association/rescript-core#173]
As said in title.

**Comment by glennsl** [comment]
They're in `Int.Constants`: https://github.com/rescript-association/rescript-core/blob/main/src/Core__Int.resi#L30-L57

**Comment by dsiu** [comment]
[`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)  in js is different than `Int.Constants.maxValue`

I guess I can just make a binding in my project.

Thanks.

**Comment by glennsl** [comment]
I guess it depends what you need it for. `MAX_SAFE_INTEGER` wouldn't be safe to represent as an `int` in Rescript, so including it would likely cause confusion and errors. For the rare edge case where you need to know what you can safely represent as an integer in a `float`, it's probably best to bind to it yourself, indeed.

**Comment by DZakh** [comment]
I think it won't harm adding it to `Float.Constants`
