### ISSUE TITLE
Add Dict.map

### ISSUE THREAD

**Issue by Minnozz** [rescript-association/rescript-core#179]
I was [migrating a library](https://github.com/nkrkv/jzon/pull/19) to use `@rescript/core` and was unable to find an alternative for `Js.Dict.map` in either Belt or this library. Should it be added?

**Comment by Minnozz** [comment]
For reference, the implementation of `Js.Dict.map`:
https://github.com/rescript-lang/rescript-compiler/blob/0bd73673276decaf5a35116a0a28a3d67887d881/jscomp/others/js_dict.res#L115-L124

**Comment by zth** [comment]
Oh yeah, that definitely sounds like a good idea. Care to PR?

**Comment by DZakh** [comment]
Should we call it `mapValues`? Like it's in lodash https://lodash.com/docs/4.17.15#mapValues

Also, https://lodash.com/docs/4.17.15#mapKeys can be handy as well

**Comment by Minnozz** [comment]
I added `mapValues` and some other bindings that I needed in #181.
