### ISSUE TITLE
Localized date functions

### ISSUE THREAD

**Issue by dkirchhof** [rescript-association/rescript-core#28]
Hello,

is there a reason, why the functions like `toLocaleDateString` don't except a locale string?
If there is no reason, I could create a PR with additional functions like `toLocaleDateStringWithLocale` or add optional params to the existing functions.

Cheers
Daniel

**Comment by zth** [comment]
No, that's probably just an oversight. Please do PR that. Check the naming scheme for other similar functions and try to stick close to that.

Thank you for contributing!
