### ISSUE TITLE
BigInt.toInt could be zero-cost

### ISSUE THREAD

**Issue by illusionalsagacity** [rescript-association/rescript-core#31]
Small thing, if wanting to some compile-time overhead. It also [is a good deal faster for me](https://jsbench.me/ysle4msbsi/1) at runtime 

<img width="579" alt="Number constructor and bitwise coersion 36.94% slower than BigInt.asIntN(32)" src="https://user-images.githubusercontent.com/1661092/218836698-e0b07a56-7ce9-4f39-b88c-3530d36340be.png">

https://github.com/rescript-association/rescript-core/blob/main/src/Core__BigInt.res#L16

```rescript
@scope("BigInt")
external toInt: (@as(32) _, bigint) => int = "asIntN"
```

Sure would be nice if we could bind a rescript external function to a js expression for the `**`:

```rescript
external exp: (t, t) => t = %rawExpression("%{1} ** %{2}")
```

**Comment by illusionalsagacity** [comment]
My mistake, this doesn't actually convert to `Number` unfortunately.

**Comment by zth** [comment]
Shoot! 😄
