### ISSUE TITLE
Intl.PluralRules typo in select binding

### ISSUE THREAD

**Issue by illusionalsagacity** [rescript-association/rescript-core#64]
https://github.com/rescript-association/rescript-core/blob/main/src/intl/Core__Intl__PluralRules.res#L19

bound to `format`, not `select`.

**Comment by cknitt** [comment]
Similar issue here with `formatRange` vs. `formatRangeToParts`:

https://github.com/rescript-association/rescript-core/blob/4e73a95c6ac4db2befeaa5b50089b0be88389e2a/src/intl/Core__Intl__DateTimeFormat.res#L35
