### ISSUE TITLE
Plans for Belt Map and Set?

### ISSUE THREAD

**Issue by jmagaram** [rescript-association/rescript-core#96]
I've used the Belt Map and Set and find them useful and much better than the built-in JavaScript ones. They let you define a key comparator and are immutable. Are there plans to include these? If not I will need to use Belt in addition to Core. Also curious why List is included but not the Belt Set and Map since this is not a core JS type.

**Comment by zth** [comment]
They won't be included. Using Belt for use cases needing those is fine and encouraged. List and a few other modules are included to ease the transition of eventually bringing this into the compiler.
